version: 2
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    working_directory: ~/DemoCircleAndroid
    steps:
      - checkout
      - run:
          name: Assemble & Test (Amazon Flavour)
          command: ./gradlew assembleWithAmazon testWithAmazonDebugUnitTest
          environment:
            TERM: dumb
      - run:
          name: Assemble & Test (Google Flavour)
          command: ./gradlew assembleWithGoogle testWithGoogleDebugUnitTest
          environment:
            TERM: dumb